### ISSUE TITLE
finalizing setup script: limbo?

### ISSUE THREAD

**Issue by diehard88** [41Team/RoutersploitTermux#4]
`

> echo "[*] All installation is done. Clearing up installation script..."
> rm -rf $HOME/RoutersploitTermux
> rm -rf $HOME/run.sh
> sleep 1
> clear
> echo "[*] All done!"
> echo Run routersploit with command
> echo cd routersploit and python rsf.py 

`

The RoutersplotTermux folder is forcibly removed while we are still inside it.   After exiting the script, we're in limbo.

:)

**Comment by Mrcose** [comment]
Thanks for the help! I will fix the script as soon as possible
